name: test01
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.2+1
  geolocator: ^14.0.2
  http: ^1.5.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  flutter_email_sender: ^8.0.0
  connectivity_plus: ^6.1.5
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  video_player: ^2.11.1
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/infografias/
    - assets/images/emergency/
    - assets/images/garabato_chatbot/
    - assets/images/garabato_informacion/
    - assets/videos/
